import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Button, Card, CardBody, Center } from '@chakra-ui/react'
import { useEffect, useState } from 'react'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import { Auth } from '@supabase/auth-ui-react'
import { ThemeSupa } from '@supabase/auth-ui-shared'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const supabaseClient = useSupabaseClient()
  const user = useUser()
  const [data, setData] = useState<any>();

  useEffect(() => {
    async function loadData() {
      const { data } = await supabaseClient
      .from('AuthKey')
      .select('*');
      
      setData(data);
    }
    // Only run query once user is logged in.
    if (user) loadData()
  }, [user]);

  if (!user)
    return (
        <Box maxW="960px">
          <Auth
            redirectTo="http://localhost:3000/"
            appearance={{ theme: ThemeSupa }}
            supabaseClient={supabaseClient}
            providers={['google', 'github']}
            socialLayout="horizontal"
            localization={{
              variables: {
                sign_in: {
                  email_label: 'Email',
                  password_label: 'Contraseña',
                },
              },
            }}
          />
        </Box>
    )

  return (
    <>
      <Head>
        <title>Saya Montessori | Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Center>Saya Web</Center>
        <Button onClick={() => supabaseClient.auth.signOut()}>Cerrar Sesion</Button>
        <p>user:</p>
        <pre>{JSON.stringify(user, null, 2)}</pre>
        <p>client-side data fetching with RLS</p>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
    </>
  )
}
